name: jewels
description: "JewelTry - AR Jewelry Try-On App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Camera & AR
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.0

  # Local storage
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  # Image handling
  image_picker: ^1.1.2

  # Utils
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jewelry/
